title: Webdevelopment for dummies workshop
description: Here you can easily download slides and navigate to the source code for these workshops.
show-downloads: false
theme: jekyll-theme-minimal
remote_theme: "dracula/gh-pages"
plugins:
  - jekyll-remote-theme